"""Added cart default values

Revision ID: 246cff4af733
Revises: 5bb504e394a0
Create Date: 2022-11-17 11:32:55.818206

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '246cff4af733'
down_revision = '5bb504e394a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
