"""Added book relationship in user model and on delete in book model

Revision ID: 24e4d867bd80
Revises: 2f218367ac92
Create Date: 2022-11-16 07:44:33.469074

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '24e4d867bd80'
down_revision = '2f218367ac92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_user_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_user_id_fkey', 'book', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
