"""Added cartitem quantity attribute

Revision ID: 71d80456b6ad
Revises: 246cff4af733
Create Date: 2022-11-17 16:36:34.056663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d80456b6ad'
down_revision = '246cff4af733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartitem', 'quantity')
    # ### end Alembic commands ###
